name = "mawoka-website"
type = "javascript"
route = ''
account_id = '5918227f6e841f8ab2c6af0a8f2e5355'
zone_id = '76158640f3b8d468706945766fd5a003'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "./workers-site"}
compatibility_date = "2021-09-23"

[build]
# Assume it's already been built. You can make this "npm run build" to ensure a build before publishing
command = ""

[build.upload]
format = "service-worker"